// Autogenerated from Pigeon (v0.1.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTProtoWrapper;

@interface FLTProtoWrapper : NSObject
@property(nonatomic, strong, nullable) FlutterStandardTypedData * proto;
@end

@protocol FLTFitApi
-(void)initialize:(FlutterError *_Nullable *_Nonnull)error;
-(void)dispose:(FlutterError *_Nullable *_Nonnull)error;
-(nullable FLTProtoWrapper *)getActivityType:(FLTProtoWrapper*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable FLTProtoWrapper *)listActivityLogs:(FLTProtoWrapper*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTFitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTFitApi> _Nullable api);

NS_ASSUME_NONNULL_END
