// Autogenerated from Pigeon (v0.1.22), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTBoolValue;
@class FLTProtoWrapper;

@interface FLTBoolValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface FLTProtoWrapper : NSObject
@property(nonatomic, strong, nullable) FlutterStandardTypedData * proto;
@end

@protocol FLTGoogleFitApi
-(void)initialize:(FlutterError *_Nullable *_Nonnull)error;
-(void)dispose:(FlutterError *_Nullable *_Nonnull)error;
-(void)checkPermission:(void(^)(FLTBoolValue *_Nullable, FlutterError *_Nullable))completion;
-(nullable FLTProtoWrapper *)getActivityType:(FLTProtoWrapper*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)aggregate:(nullable FLTProtoWrapper *)input completion:(void(^)(FLTProtoWrapper *_Nullable, FlutterError *_Nullable))completion;
-(void)sessionsList:(nullable FLTProtoWrapper *)input completion:(void(^)(FLTProtoWrapper *_Nullable, FlutterError *_Nullable))completion;
-(void)readDailyTotal:(nullable FLTProtoWrapper *)input completion:(void(^)(FLTProtoWrapper *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTGoogleFitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTGoogleFitApi> _Nullable api);

NS_ASSUME_NONNULL_END
